In [2]:
import pandas as pd

In [3]:
dframe = pd.read_csv('DOH COVID Data Drop_ 20220917 - 04 Case Information_batch_3.csv')

C:\Users\baja0\AppData\Local\Temp\ipykernel_12476\3323693458.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  dframe = pd.read_csv('DOH COVID Data Drop_ 20220917 - 04 Case Information_batch_3.csv')

In [6]:
health_status = dframe[(dframe.HealthStatus != 'RECOVERED') & (dframe.HealthStatus != 'DIED')]
health_status

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
33380,C184203,29.0,25 to 29,FEMALE,2022-01-08,2022-01-09,2022-01-12,NaN,NaN,NaN,...,BATAAN,MARIVELES,PH030807000,TOWNSITE,PH030807020,MILD,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
183624,C72317810,49.0,45 to 49,FEMALE,2022-01-11,2022-01-14,2022-01-16,2021-09-14,NaN,NaN,...,NCR,QUEZON CITY,PH137404000,CENTRAL,PH137404020,MILD,NO,NaN,NO,"Case has Lab Result, but Result Date is blank"
257392,C236300,27.0,25 to 29,MALE,2022-01-15,2022-01-16,2022-01-18,NaN,NaN,NaN,...,NCR,PASAY CITY,PH137605000,BARANGAY 183,PH137605183,MILD,NO,NaN,NaN,Age or Birthdate is Invalid\nHealth Status is ...
276650,C195533,77.0,75 to 79,MALE,2022-01-16,2022-01-17,2022-01-19,2022-01-16,NaN,NaN,...,BENGUET,BAGUIO CITY,PH141102000,AURORA HILL PROPER (MALVAR-SGT. FLORESCA),PH141102067,MILD,NO,NaN,NaN,Age or Birthdate is Invalid\nUnexpected change...
381006,C22334890,66.0,65 to 69,FEMALE,2022-01-17,2022-01-19,2022-01-22,2022-01-18,NaN,NaN,...,ZAMBOANGA DEL SUR,LABANGAN,PH097312000,BOKONG,PH097312006,MILD,NO,2021-05-04,NO,"Case has Lab Result, but Result Date is blank\..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918324,C64764865,32.0,30 to 34,FEMALE,2022-09-12,2022-09-12,2022-09-17,NaN,NaN,NaN,...,CEBU,CEBU CITY (CAPITAL),PH072217000,TISA,PH072217085,MILD,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
918325,C95923867,29.0,25 to 29,FEMALE,2022-09-14,2022-09-14,2022-09-17,NaN,NaN,NaN,...,NCR,CITY OF VALENZUELA,PH137504000,PASOLO,PH137504024,MILD,NO,2022-09-14,NO,NaN
918326,C66886479,72.0,70 to 74,FEMALE,2022-09-14,2022-09-14,2022-09-17,NaN,NaN,NaN,...,QUEZON,LUCENA CITY (CAPITAL),PH045624000,MAYAO PARADA,PH045624029,MILD,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
918327,C87440649,15.0,15 to 19,MALE,2022-09-12,2022-09-14,2022-09-17,NaN,NaN,NaN,...,LA UNION,NaN,NaN,NaN,NaN,MILD,NO,2022-09-10,NaN,NaN
918328,C54219057,27.0,25 to 29,FEMALE,2022-09-14,2022-09-14,2022-09-17,NaN,NaN,NaN,...,DAVAO DEL SUR,DAVAO CITY,PH112402000,BARANGAY 20-B (POB.),PH112402153,MILD,NO,NaN,NO,NaN

In [33]:
health_status_no_nul = health_status[health_status.BarangayPSGC.notnull()].groupby('BarangayPSGC').agg(active_cases = ('BarangayPSGC', 'count'))
health_status_no_nul

              active_cases
BarangayPSGC
PH012802007              1
PH012802008              1
PH012802012              1
PH012802015              1
PH012802019              1
...                    ...
PH175324004              1
PH175909015              1
PH175911004              1
PH175911006              1
PH175916006              1

[7561 rows x 1 columns]

In [28]:
zeroes = len(health_status) - len(health_status_no_nul)

In [11]:
MILD = health_status_no_nul[(health_status_no_nul.HealthStatus == 'MILD')].groupby('BarangayPSGC', as_index=False).agg(mild = ('HealthStatus', 'count')).sort_values('mild', ascending=False)
CRITICAL = health_status_no_nul[(health_status_no_nul.HealthStatus == 'CRITICAL')].groupby('BarangayPSGC', as_index=False).agg(critical = ('HealthStatus', 'count')).sort_values('critical', ascending=False)
SEVERE = health_status_no_nul[(health_status_no_nul.HealthStatus == 'SEVERE')].groupby('BarangayPSGC', as_index=False).agg(severe = ('HealthStatus', 'count')).sort_values('severe', ascending=False)
ASYMPTOMATIC = health_status_no_nul[(health_status_no_nul.HealthStatus == 'ASYMPTOMATIC')].groupby('BarangayPSGC', as_index=False).agg(asymptomatic = ('HealthStatus', 'count')).sort_values('asymptomatic', ascending=False)
MODERATE = health_status_no_nul[(health_status_no_nul.HealthStatus == 'MODERATE')].groupby('BarangayPSGC', as_index=False).agg(moderate = ('HealthStatus', 'count')).sort_values('moderate', ascending=False)

In [31]:
total = len(ASYMPTOMATIC) + len(MILD) + len(MODERATE) + len(CRITICAL) + len(SEVERE)

In [34]:
total_total = total - zeroes

In [35]:
len(ASYMPTOMATIC)

3460

In [36]:
len(MILD)

4947

In [37]:
len(MODERATE)

973

In [38]:
len(SEVERE)

396

In [39]:
len(CRITICAL)

169